### ISSUE TITLE
Smartypants isn’t too smart about quotes

### ISSUE THREAD

**Issue by iclanzan** [chjj/marked#166]
In words like `don't` and `'cause` the straight quote should be converted to an apostrophe (right single curly quote).

 Right now in a sentence like `I won't do it 'cause I don't want to.` the first `'` gets converted to a left single quote, the second one to a right single quote and the third is unchanged which is wrong.

**Comment by edemaine** [comment]
Update: Since #178, that sample sentence now translates to `I won’t do it ‘cause I don’t want to.`  So it's correct in the middle of a word, but [incorrect](http://www.chicagomanualofstyle.org/qanda/data/faq/topics/SpecialCharacters/faq0008.html) in `'cause`.

Relatedly, I came here to report that `[JavaScript](https://en.wikipedia.org/wiki/JavaScript)'s` formats into `<a href="https://en.wikipedia.org/wiki/JavaScript">JavaScript</a>‘s` which is also the wrong apostrophe.  I'm not quite sure why, given the current regex... is it being treated as at the beginning of line in this case?

**Comment by joshbruce** [comment]
I see this in a lot of editors and renderers...even MS Word and Apple Pages I have to open the glyph selector to do that. Only online editor I've seen get it right is Medium.

#27 

Closing as stale and merged.
