### ISSUE TITLE
Hashtags in the beginning are rendered as headings

### ISSUE THREAD

**Issue by jorilallo** [chjj/marked#201]
I ran into a problem while testing hashtags:

    marked("#hashtag test\n test")

renders as

```
<h1>hashtag test</h1>
<p> test</p>
```

while the expected output is

```
<p>#hashtag test</p>
<p> test</p>
```

**Comment by silkimen** [comment]
+1 GFM

**Comment by chjj** [comment]
Fixed.

**Comment by xaka** [comment]
I know it's been a while, but for the future reference I want to point out that this change should have never landed as a patch (0.3.2 -> 0.3.3), but at least as a minor (0.3.2 -> 0.4.0) because it's backward incompatible from customer's perspective, who don't care about whitespace because it's been allowed for a long time and now it breaks existing badly formatted markdowns. No complains whatsoever. Just suggestions :wink:

**Comment by Stephen-Mc** [comment]
Very unhappy at this change, it broke all our documentation by no longer rendering the headings correctly. Would love to see it reverted, as breaking existing docs just to be able to render hashtags without an escape character does not strike me as the right set of priorities.

Thankfully most of our docs are parsed for conversion to HTML, and are still rendered correctly on our websites, but I have 100 or so pages that are not parsed this way and now need to be updated with the new heading style.

**Comment by zcyzcy88** [comment]
How about `<h1>` require space, and `<h2>`~`<h6>` don't require space?
Because people are used in Twitter style text, when they type `#`, it means hashtag, not heading.

---

**Example:**
```md
Text Text Text Text Text Text Text Text.
#tag1 #tag2
```

---

**Now render as:**

Text Text Text Text Text Text Text Text.
# tag1 #tag2

---

**Expect:**

Text Text Text Text Text Text Text Text.
#tag1 #tag2

**Comment by Stephen-Mc** [comment]
That would be even more confusing than the current state of affairs.

**Comment by Grey2k** [comment]
#hashtag# test
