### ISSUE TITLE
HTML comments are included in p tag

### ISSUE THREAD

**Issue by adius** [chjj/marked#253]
When using

```
var tokens = marked.lexer(text, options)
marked.parser(tokens)
```

HTML comments will get included into a p tag and so be visible in the output!

**Comment by alexilyaev** [comment]
Is there any update on this one?

Testing with:
```
<!-- Test Comment -->
```
Result:
```html
<p>&lt;!-- Test Comment --&gt;
</p>

```

**Comment by f03lipe** [comment]
Bump?

**Comment by f03lipe** [comment]
Bump?

**Comment by travs** [comment]
+1 :+1:

**Comment by bryanjacquot** [comment]
+1

**Comment by joshbruce** [comment]
#985

**Comment by Feder1co5oave** [comment]
If you're **sanitizing** your input, it means you're not _allowing_ html elements to be left as-is in the output. So why are you expecting `marked` to hide html comments?

Or maybe, you're trying to leave (invisible) comments in your markdown, but do not want to allow html in it. And that could be interesting too.
The fix could be to not escape html comments as an exception, so that they would be hidden in the html render.
