### ISSUE TITLE
pre's inside html

### ISSUE THREAD

**Issue by ianstormtaylor** [chjj/marked#378]
Marked does an awesome thing where it lets you write markdown formatted strings inside HTML inside your markdown, so that you can for example make a `<table>` or `<figure>` and not have to resort to using `<strong>` or `<em>`. That is sweet.

Just ran into an issue though where `<pre>` tags aren't getting properly skipped for that inline formatting. Basically the [check for whether to skip a block](https://github.com/chjj/marked/blob/master/lib/marked.js#L362) of HTML only checks the parent element, instead of nested `<pre>` tags, so an example like this will still have inline formatting applied:

``` html
My _markdown_ here...

<figure>
  <pre data-language="javascript"><code>
    Sample code that might contain things that _look_ like markdown.
  </code></pre>
  <pre data-language="ruby"><code>
    Sample code that might contain things that _look_ like markdown.
  </code></pre>
</figure>

More of my markdown down **here**.
```

In this case, since the top-level tag is `<figure>` Marked is still applying the inline formatters to the entire block, even though all of the `<pre>` children shouldn't have them applied.

**Comment by lindyblackburn** [comment]
If you can run javascript, you can set "marked.setOptions({pedantic: false});" to avoid marked breaking from the markdown spec and interpreting inside html blocks altogether.

Otherwise quick fix is to just use markdown (triple backticks, etc) inside the html blocks to set preformatted text or include \\*, etc.

@rymohr I think the html blocks need to be surrounded by blank lines.

**Comment by joshbruce** [comment]
#983
