### ISSUE TITLE
Can't italicize substring.

### ISSUE THREAD

**Issue by jwerre** [chjj/marked#599]
When I try to italicize a substring like this:

```
_this_ should be ita_li_c
```

the output is:

```
<em>this</em> should be ita_li_c
```

Shouldn't it be:

```
<em>this</em> should be ita<em>li</em>c
```

I should mention bold works as expected:

```
__This__ t__ex__t should be bold

<strong>This</strong> t<strong>ex</strong>t should be bold
```

[codepen](http://codepen.io/jwerre/pen/GJrpjV)

**Comment by Mashkin** [comment]
This is indeed a difference with [GitHub flavoured Markdown][gfm] (GFM) which is enabled by default.
>    Where Markdown transforms underscores (_) into italics, GFM ignores underscores in words
To disable this behaviour, one has to set both `pedantic: true` and `gfm: false`; I can't say whether this behaviour is also an intentional part of non-pedantic Markdown.

However, you can also use `*` (asterisks) to italize word portions: `Ita*li*ze`: Ita*li*ze

[gfm]: https://help.github.com/articles/github-flavored-markdown/

**Comment by mmahalwy** [comment]
*sdfsdf*

**Comment by Feder1co5oave** [comment]
Not relevant anymore. GFM conforms to commonmark now. Underscores don't emphasize intra-word.
https://github.github.com/gfm/#emphasis-and-strong-emphasis

```markdown
_this_ should be ita_li_c

__This__ t__ex__t should be bold
```
gives
~~~html
<p><em>this</em> should be ita_li_c</p>
<p><strong>This</strong> t__ex__t should be bold</p>
~~~
