### ISSUE TITLE
Is The Blockquote Error?

### ISSUE THREAD

**Issue by mzaini30** [chjj/marked#602]
I had writing `> test` but become `> test` without blockquote. Why?

**Comment by lindstrm** [comment]
I noticed the same error.

**Comment by glantucan** [comment]
Me too!!

**Comment by dongwq** [comment]
use $('#content').text() to get text works for me.

**Comment by EverlessDrop41** [comment]
I'm getting the same thing!

**Comment by leoyli** [comment]
This issue should be closed.  Since that's the issue is from the user not the lib itself.

Check the data string first to see if it `>` rather than `/&gt;`.  If your input is from server, it is possible to get `/&gt;+` instead.  In that case, just replace your string using `.replace(/&gt;+/g, '>')` before put it into `marked()`.

**Comment by Feder1co5oave** [comment]
Works as expected:

```
$ bin/marked
> test
^D
<blockquote>
<p>test</p>
</blockquote>
```
