### ISSUE TITLE
Adopting maintainers, accepting/rejecting PRs, making releases

### ISSUE THREAD

**Issue by rgbkrk** [chjj/marked#618]
This package is great! It would be nice to see additional maintainers come aboard that can help triage existing issues and PRs. After filing my own PRs and issues (with no commentary), I've noticed that :new: PRs and issues have come up without resolution.

Would there be a path for adding additional maintainers to this package to help with outstanding PRs or issues?

I'm happy to help and fairly well versed in working with lots of collaborators to a project while applying the direction of a project as best I can (in this case, sticking to the [philosophy behind marked](https://github.com/chjj/marked#philosophy-behind-marked)). Please let me know if I or others can help!

/cc @chjj @ChrisWren @minrk @jdfreder

**Comment by mercmobily** [comment]
Three days and no answer... @chjj i think this is a great offer!

**Comment by chjj** [comment]
I try to set aside a day where I do nothing but PRs, but it gets trying. I'm open to more maintainers, which is why I've added a few others already.

To be comfortable with someone maintaining the code and accepting PRs, I'd have to know that they understand the code, and know, like you said, that they understand the philosophy of marked (__fast__, one file, the right balance of accurate features vs. intuitive features).

The trouble is, marked is written in such a bizarre way in order to optimize it that it's not easy to understand the code at this point (even for me sometimes). For example, if you change a regex, you better understand _every_ character of that regex, and which regex features produce faster or slower machine code in v8. For every one line change you make, you'd better run the benchmarks 3 or 4 times.

Maybe another way to do it, is if a maintainer doesn't understand a particular piece of code or regex to ping/email me (I'm not trying to say I'm smarter than everyone or anything like that: half the time I look at the code __I__ can forget why a regex is written a certain way, etc).

I could also document every line of the current code, but that would take a lot of time and explaining.

Then again, the test suite is thorough (so thorough it looks like it's been borrowed by many other projects). Maybe that's good enough most of the time. Run tests and benchmarks (several times) for every change.

@rgbkrk, who else did you have in mind?

**Comment by chjj** [comment]
Here is a good example of what I mean of "accuracy vs. intuition": https://github.com/chjj/marked/blob/master/doc/broken.md

Markdown is broken. People expect it to behave a certain way and the original implementation (and even GFM for some things) does not behave the way one would expect, or in a reasonable way.

**Comment by minrk** [comment]
Hooking up CI for benchmarks might be a valuable addition, to keep an eye on performance effects of PRs. [asv](http://asv.readthedocs.org/) may be useful for this. There may be a js analog that I'm not aware of.

**Comment by rgbkrk** [comment]
Thanks for the response @chjj!

In my case, the "else" I have in mind is likely other Jupyter and IPython developers. We use `marked` and `term.js` for the IPython notebook which is used by lots of researchers, scientists, and data scientists the world over. We'd prefer to help with existing community packages instead of creating complete forks ourselves.

At least for me, I think some mentoring time is useful. I can start learning more about profiling the current implementation as well as against, e.g. [commonmark.js](https://github.com/jgm/commonmark.js).

**Comment by rgbkrk** [comment]
@chjj What do you think about @Pomax as an additional maintainer?

**Comment by Pomax** [comment]
This would probably be a bad plan, given my time constraints =(

**Comment by chjj** [comment]
> This would probably be a bad plan, given my time constraints =(

This usually ends up being the problem. A new maintainer will eventually get roped into something else; including myself.

I would also prefer people who have posted PRs here that follow marked's design closely. It's hard to pick maintainers if I don't know what they're capable with when it comes to marked.

**Comment by joshbruce** [comment]
See #956
