### ISSUE TITLE
Ordered lists cannot be completely override

### ISSUE THREAD

**Issue by jdrydn** [chjj/marked#665]
Hi there,

I'm using Marked on my website and I'm trying to override the `list` functions to stop an ordered list being created in certain scenarios:

```
7. Here is some example text.
```

Ideally should become:

``` html
<p>7. Here is some example text.</p>
```

Now, obviously I'm getting the default Markdown behaviour:

``` html
<ol>
<li>Here is some example text.</li>
</ol>
```

Yet neither `list` nor `listitem` will allow me to change the output of the list. I've checked both functions to see what they provide as their `body` argument, and both `body` arguments are the `<li>` tag, so whatever I return will be children of the `<ol></ol>` tag so therefore I cannot remove the `ol` tags at all.

Is there any other function I could use to override the list in this case?

**Comment by Feder1co5oave** [comment]
You didn't specify what "certain scenarios" mean.
Anyway, I can't understand what you mean with your last paragraph. If you want to suppress the generation of a list you should override `list` and `listitem` in a custom renderer. The latter takes in as `body` argument

**Comment by jdrydn** [comment]
Imagine a blog post where it's "*Top 10 reasons to use Marked*", and a visitor leaves a comment with the content:

```
11. Here is another awesome reason to use Marked!
```

At the moment, if you run that content through `marked` it'll spit out:

```
<ol>
<li>Here is another awesome reason to use Marked!</li>
</ol>
```

Which of course will be rendered as:

```
1. Here is another awesome reason to use Marked!
```

Which is obviously not what the original input was!!

I'm gonna return to experimenting with `list` and `listitem`, but IIRC it still added the `<ul>`/`<ol>` tags when using both which caused the number to reset!

**Comment by isiahmeadows** [comment]
I have another use case, if this might help: I'm writing a custom renderer that parses regular Markdown, but instead of printing HTML, it prints an equivalent, markdown-ish version that doesn't use newlines, for previews to be loaded via XHR. In my case, I need to either be able to return an object from `listitem` or know in `listitem` if it's in an ordered list or not, so I can return the appropriate prefix. Currently, I'm hacking around it this way (by using a primitive string serialization technique), but it's far from ideal:

```js
class Renderer {
    // ...

    listitem(text) {
        // Using tabs (which are never used) to deal with the fact Marked has no
        // way to return this to `list` or know if this is in an ordered list.
        return `\t${text.replace(/\s+/g, "")}`
    }

    list(body, ordered) {
        if (ordered) return body.replace(/\t/g, " - ")
        // It's a safe assumption that the first character is a tab
        const parts = body.slice(1).split(/\t/g)
        let ret = ""
        for (let i = 0; i < parts.length; i++) {
            ret += `${i}. ${parts[i]}`
        }
        return ret
    }

    // ...
}
```

Ideally, the parser shouldn't assume that the renderer only returns strings. Every React port of this either has to write their own parser or literally fork Marked altogether. And every other vdom library will suffer similarly as well.

Granted, for my uses, despite the superficial simplicity, I will likely have to implement my own parser from Markdown's lexer. Although it's not ideal, it's not as hard as it could be, since I'm literally just building a string from a stream of tokens.

**Comment by joshbruce** [comment]
#982
