### ISSUE TITLE
Lists with code fences work incorrectly if code contains "[" symbol

### ISSUE THREAD

**Issue by evil-shrike** [chjj/marked#712]
input.md:

``````
1. see code:  
\```
__newValues?: {
    [key: string]: any;
}
\```
2. next item
``````

In `token` method "list" rule captures list items:

```
    // list
    if (cap = this.rules.list.exec(src)) {
      src = src.substring(cap[0].length);
```

here `src` will be: 

``````
 [key: string]: any;
}
\```
``````

I added "\" before block fence.

**Comment by Feder1co5oave** [comment]
Why did you add the backslashes? What is the output you expect from that source?

**Comment by evil-shrike** [comment]
@Feder1co5oave I added backslashes to prevent parsing this markdown here (by github). Actual source input.md has no "\".

**Comment by Feder1co5oave** [comment]
Ouch, you're right. This does look nasty!
I believe the problem is that `[key: string]: any;` is interpreted as a "definition" (a link reference that you usually put at the end of the document, but is expected to be found also inside other elements like lists and blockquotes).
Moreover, the output changes whenever the indentation of that code block is changed (I'm used to indent the content of a list item). I was able to get the correct output by applying the following patch:
```diff
diff --git a/lib/marked.js b/lib/marked.js
index 0711b00..d4e34e9 100644
--- a/lib/marked.js
+++ b/lib/marked.js
@@ -19,7 +19,7 @@ var block = {
   nptable: noop,
   lheading: /^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,
   blockquote: /^( *>[^\n]+(\n(?!def)[^\n]+)*\n*)+/,
-  list: /^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,
+  list: /^( *)(bull) [\s\S]+?(?:hr|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,
   html: /^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,
   def: /^ *\[([^\]]+)\]: *<?([^\s>]+)>?(?: +["(]([^\n]+)[")])? *(?:\n+|$)/,
   table: noop,
```

However that lists regex definitely needs to be reviewed.

You can also easily work around this by putting a space between the `]` and the `:`

**Comment by joshbruce** [comment]
#982
