### ISSUE TITLE
feature request : optional MathJax support

### ISSUE THREAD

**Issue by Jasper0819X** [chjj/marked#722]
Here‘s an example, which works:

https://gist.github.com/3846masa/cde99a18a8d7ad225cf7

**Comment by rhauteki** [comment]
[KaTeX](https://github.com/Khan/KaTeX) is the future of math typesetting for the web.

KaTex vs. MathJax:
![katex-comparison](http://khan.github.io/KaTeX/katex-comparison.gif)

**Comment by rhauteki** [comment]
I've submitted a pull request #723 to ignore everything between $ or $$ to allow the use of KaTeX or MathJaX so the user doesn't have to worry about using _ or * in TeX formulas

**Comment by MrJasper** [comment]
Thanks a lot for your work, and sorry for my late...
I've tested your code in vscode and found a bug:

![bug](https://cloud.githubusercontent.com/assets/15362491/13379482/abf381c6-de61-11e5-83dc-cef6f1034f01.png)

how to fix it? I know little about js.

**Comment by rhauteki** [comment]
Thanks for pointing out, I guess I should've made it a block-level grammar rule, I'll change the code and do so more extensive testing ...

**Comment by Feder1co5oave** [comment]
I implemented this a while ago to use it with MathJax (I'll definitely have a glance at KaTeX since it looks promising). I use it regularly and I find it is quite stable.

https://github.com/chjj/marked/compare/master...Feder1co5oave:0341a2f

Basically you parse your markdown which includes `$ ... $` (inline math) and `$$ ... $$` (block level displaymath) tags, and then run `MathJax.Process` on the container you put your generated html code into.

**Comment by anaderi** [comment]
would be nice to have it merged if no issues are found. (works fine for me so far)

**Comment by wookayin** [comment]
Any updates?

**Comment by joshbruce** [comment]
Closing for now. Please see #956 

See two targeted Markdown specifications.
