### ISSUE TITLE
How to override render method of <img>

### ISSUE THREAD

**Issue by poberwong** [chjj/marked#774]
I want to override method of `<img>`, However, I find that `<img>` is not recognized as html.
the following method is which I override:

```
Renderer.prototype.html = function(html) {
  return html;
};
```

so, which part should be override ?

**Comment by joshbruce** [comment]
#989

**Comment by fxha** [comment]
I think I have a similar issue with `img` tags because inline `img` tags are not recognized as HTML nor image. Is this the expected behavior?

**Example:**

1\. Block `<img>` tag is recognized as HTML.

```
foo

<img src="./img1.png">

bar
```

2\. Inline `<img>` tag is not recognized as HTML and also not as image but `![]()` is recognized as image.

```
foo

foo ![img1](./img1.png) bar <img src="./img1.png"> foobar

bar
```

**Comment by UziTech** [comment]
@fxha Inline HTML is just plain text according to the commonmark spec so the only way to modify it would be to search for it before passing the string to marked.

```js
const md = `foo

foo ![img1](./img1.png) bar <img src="./img1.png"> foobar

bar`;

md.replace(/<img .*?>/, 'Something else');

marked(md);

```

**Comment by styfle** [comment]
Depending on your use case, you might want to filter out all images by using an allow-list of html tags 

See this comment 
https://github.com/markedjs/marked/issues/1388#issuecomment-447048317
