### ISSUE TITLE
iframe is not parsed

### ISSUE THREAD

**Issue by naivefun** [chjj/marked#861]
```
<iframe width="853" height="480" src="https://www.youtube.com/embed/pKg_PBN0zZo?rel=0" frameborder="0" allowfullscreen></iframe>
```

This element is not parsed/rendered , is there any settings I need update for iframe? Thanks.

**Comment by Flux159** [comment]
I had this same issue and came up with a hack around it. Posting it here in case anyone else wants it - but it may not work for your usecase (I only needed it for adding iframes to some generated documentation).

Marked seems to sanitize iframes and scripts out of the html generated, so the following:
```html
<iframe width="1080" height="720" src="https://www.youtube.com/embed/vkwZEsGho40" frameborder="0" allowfullscreen></iframe>
```

Will be removed. However, if you do something like this:

```html
<div class="iframe" src="https://www.youtube.com/embed/vkwZEsGho40"></div>
```

That is rendered as HTML in the output.

If you have access to javascript on the page where you are rendering the html, you can then manipulate that rendered html to generate an iframe:

```javascript
window.onload = function() {
  var iframes = [].slice.call(document.getElementsByClassName('iframe'));
  for (var i = 0; i < iframes.length; i++) {
    var node = iframes[i];

    var realIframe = document.createElement('iframe');
    realIframe.width = 1080;
    realIframe.height = 720;
    realIframe.setAttribute('src', node.getAttribute('src'));
    realIframe.setAttribute('allowfullscreen', true);
    realIframe.setAttribute('frameborder', '0');

    node.appendChild(realIframe);
  }
};
```

This obviously only works if you have access to the javascript on the page. Its very hacky, but wanted to post it incase it helps someone (and since it seems like marked hasn't been updated in around half a year now - so I'm not sure when / if this issue will get looked at).

**Comment by Feder1co5oave** [comment]
Set `sanitize: false` to let any html pass through as it is

**Comment by joshbruce** [comment]
Closing as solvable.
