### ISSUE TITLE
XSS Security issue

### ISSUE THREAD

**Issue by scinos** [chjj/marked#869]
Reported by SourceClear:

https://www.sourceclear.com/registry/security/cross-site-scripting-xss-/javascript/sid-3349

**Comment by matt-** [comment]
Please don't post a new bug ticket just because a tool reported it. Search for existing  and report if it has not been created. The details from sourceclear even list the PR.
 
There are already open tickets and a PR: 
https://github.com/chjj/marked/issues/863

https://github.com/chjj/marked/pull/844

**Comment by scinos** [comment]
Well, technically there is no other open issue mentioning 'XSS', 'Security' or 'Sourceclear' in the title. Feel free to close this if you think it is a dupe.

Good to see that the issue is actually being resolved.

**Comment by matt-** [comment]
Technically if you search XSS you can find the issue I linked above (despite it's unfortunate title).
https://github.com/chjj/marked/search?q=xss&state=open&type=Issues&utf8=%E2%9C%93

Also if you actually read in the details of the sourceclear link you posted it links to the PR so no question this is a dupe.
