### ISSUE TITLE
Table parser need to wrap line between table and paragraph

### ISSUE THREAD

**Issue by YingdaBeyondsoft** [chjj/marked#889]
I use the marked.js to parser md content for html preview.

For example of the content:
This is paragraph
|Head1|Head2|Head3|
|-------|-------|-------|
|    A    |    B    |    C    |

Get the result below:
![image](https://cloud.githubusercontent.com/assets/13430770/25474992/de09782e-2b67-11e7-948e-9f1cfa7007a3.png)

It should work fine look like below:
![image](https://cloud.githubusercontent.com/assets/13430770/25475059/1be50a14-2b68-11e7-9362-1d99152bc2c1.png)

**Comment by joshbruce** [comment]
See #980

**Comment by Feder1co5oave** [comment]
[gfm] has no clear specification on whether tables can interrupt paragraphs or not.
If you put an empty line between the paragraph and the table, like this:
```markdown
paragraph

|Head1|Head2|Head3|
|-------|-------|-------|
| A | B | C |
```
it is parsed as expected by marked:
~~~html
<p>paragraph</p>
<table><thead>
<tr><th>Head1</th><th>Head2</th><th>Head3</th></tr>
</thead><tbody>
<tr><td>A</td><td>B</td><td>C</td></tr>
</tbody>
</table>
~~~
It is more readable this way, and also much easier to parse, because we can very simply end paragraphs when we detect an empty line instead of having to check if we are encountering a table.

[gfm]: https://github.github.com/gfm/#tables-extension-
