### ISSUE TITLE
async support 

### ISSUE THREAD

**Issue by pod4g** [chjj/marked#896]
I define a special markdown syntax for our editor

the syntas like this:

\`\`\`sku
 1120
\`\`\`

the number is a id， I should fetch data by ajax (http://x.x.x.x/?id=1120)， and then i will convert the data to html , but marked not support async

What should I do?

I think this solution is pretty good #798

Relevant issues: #458

thanks for any reply !

**Comment by pod4g** [comment]
the data like this:
```js
{
 title: '天王盖地虎，宝塔震河妖',
 price: '￥250',
 image: '//content.image.alimmdn.com/sku/1463573933Q3cRJL_jpg.jpeg@200w_200h_1e%7C200x200-5rc'
}
```
convert the data to html

```html
 <div class="sku-card">
  <h1 class="sku-title">天王盖地虎，宝塔震河妖</h1>
  <img src="//content.image.alimmdn.com/sku/1463573933Q3cRJL_jpg.jpeg@200w_200h_1e%7C200x200-5rc">
 <span class="sku-price">￥250</span>
</div>
```

**Comment by Feder1co5oave** [comment]
You should override the code renderer in such a way that whenever `lang == 'sku'` you should return a `<script>` element whose code somehow performs the ajax request and then `document.write`s the content into the page.

**Comment by joshbruce** [comment]
Alternatively, you should be able to do it after the build. Seems like we are trying to make Markdown (and Marked) do more than it was intented to - convert Markdown to HTML based on specifications.

```
```sku
1120
```

Bcomes something like this
<code><pre>...</pre></code>
```

Might be more reasonable to do something like:

```
...markdown, markdown, markdown

<div class="sku-card" data-sku="1120"></div>

...markdown, markdown, markdown
```

Once the HTML is rendered, run the JS selector for `data-sku` - perform AJAX/J and build internals HTML. Also, for semantic HTML purposes may want to consider a different header level, or using an `<article>` for each sku-card instead of the div...so, if you're feeling particularly daring (and possible semantically incorrect).

```
<article is="sku-card" data-sku="1120"></article>

Becomes:

<article is="sku-card" data-sku="1120">
  <h1>...</h1>
  <img>
  <span>...</span>
</article>
```

You shouldn't need the extra classes because the wrapper says what you're playing with. If you use those components outside of the sku-card, then by all means continue using the classes or faux object inheritance.

Closing.
