### ISSUE TITLE
Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by CQBoyBrand** [chjj/marked#969]
![这里写图片描述](http://img.blog.csdn.net/20171208101757069?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvc2luYXRfMzM5Njg1MTI=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

### my code
![my code](http://img.blog.csdn.net/20171208102114377?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvc2luYXRfMzM5Njg1MTI=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
![my code](http://img.blog.csdn.net/20171208102152331?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvc2luYXRfMzM5Njg1MTI=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

## need your help~~~~ thanks!

**Comment by idflores** [comment]
@CQBoyBrand I just had this issue today as well. Pretty much identical. I **highly** recommend, take a look at your code (*** possible error ***):
```JavaScript
computed: {
    compiledMarkdown: function() {
        return marked(***this.articleDetail.artContent***, {
            sanitize: true
        })
    }
},
```
_Make sure `this.articleDetail.artContent` is returning what you think it's returning._ 

After tracing the callstack back and debugging the marked.js library itself, I found the library wasn't in the wrong at all, in my case. The error stems from the variable `src` for `marked(src, opt, callback)` (basically what I put in *** ***). `src` is handed to `Lexer` before getting parsed.  Currently, `marked()` has no way to deal with `src` if it gets passed as `undefined`, so `Lexer` takes the hit and displays the error. 

(for @joshbruce ) Perhaps add some error reporting for `marked()` if `src` ends up `undefined` 🤔? That way it's pretty clear the issue is not the `marked` library...

@CQBoyBrand If that doesn't work, `this` can do some weird things. Check that you have `use strict;` in the file, and since you're using Vue.JS, it's possible you forgot to `bind(this)` (a long shot... coming from ReactJS over here). Either way, I'm fairly convinced it's not `marked`...

**Comment by CQBoyBrand** [comment]
@idflores  thank you,The problem has been solved;
```
compiledMarkdown: function() {
      return marked(this.articleDetail.artContent || '', {
        sanitize: true
      })
    }
```
