### ISSUE TITLE
A possible lexer regression since 0.3.7

### ISSUE THREAD

**Issue by gromnitsky** [chjj/marked#978]
In 0.3.7:

~~~
> marked.lexer("foo\n[bar]: https://example.com")
[ { type: 'paragraph', text: 'foo' },
  links: { bar: { href: 'https://example.com', title: undefined } } ]
~~~

But in the current ver, the link is being recognized only if an additional newline after the "foo" string is present:

~~~
> marked.lexer("foo\n[bar]: https://example.com")
[ { type: 'paragraph', text: 'foo\n[bar]: https://example.com' },
  links: {} ]

> marked.lexer("foo\n\n[bar]: https://example.com")
[ { type: 'paragraph', text: 'foo' },
  links: { bar: { href: 'https://example.com', title: undefined } } ]
~~~

**Comment by joshbruce** [comment]
Please confirm "current version" is 0.3.9

Given that all tests pass for 0.3.9, it's possible that there were no tests related to this use case. Would you be willing and able to submit a PR with passing test cases. Also, check #956 and the specs we are supporting and ensure this is expected behavior based on those specs.

Thank you!

**Comment by gromnitsky** [comment]
> Please confirm "current version" is 0.3.9

yes, I was referring to 0.3.9

**Comment by gromnitsky** [comment]
it turns out that the new behavior is indeed 'standard'. see #987

**Comment by joshbruce** [comment]
@gromnitsky - Thanks for closing this.
