### ISSUE TITLE
Github says that marked has potential security vulnerabilities

### ISSUE THREAD

**Issue by RusinovAnton** [chjj/marked#997]
Hello.
I want to inform that I see notifications about potential security vulnerabilities in  https://github.com/chjj/marked which is dependency of some dependency of my library.
Here is links to vulnerabilities description:
https://nvd.nist.gov/vuln/detail/CVE-2017-1000427
https://nvd.nist.gov/vuln/detail/CVE-2017-17461

![image](https://user-images.githubusercontent.com/13165540/34585599-1b04a818-f1a9-11e7-909d-eb4aa7ad9dc7.png)

**Comment by hamzahamidi** [comment]
Does updating to the latest release fix the issue ?

**Comment by frederikprijck** [comment]
> Does updating to the latest release fix the issue ?

I guess it should, as the 0.3.9 release mentions:

We think with this version we have addressed most, if not all, known security vulnerabilities. If you find more, please let us know.

**Comment by RusinovAnton** [comment]
@frederikprijck 
sure some dependency haven't updated it yet. I should open issue there first. 🙄

**Comment by frederikprijck** [comment]
Yep, it looks like some packages need to update their version.

**Comment by joshbruce** [comment]
@hamzahamidi: Yes, to the best of our knowledge the XSS vulnerabilities have been fixed. However, I'm not sure what all tools exist to help us (the maintainers) verify for certain. I will defer to @matt- and @UziTech as well because I'm more the coordinator and releaser (see #956).

If any of you know how to check for certain, or how to fix other vulnerabilities we may not be aware of, please let us know or submit a PR.

I will be closing this issue for now. Please feel free to continue the conversation. And, as always, please submit PRs and issues. Thank you!

**Comment by UziTech** [comment]
As far as I know we fixed all of the open XSS vulnerabilities in v0.3.9
